from tsfit.application.usecases.train_model import TrainModelUseCase
from tsfit.application.usecases.train_model_auto import TrainModelAutoUseCase
from tsfit.application.usecases.predict import PredictUseCase
